CREATE TABLE [dbo].[IDClaim]
(
  [ID] BIGINT NOT NULL IDENTITY(1,1),
  [Database] SYSNAME NOT NULL,
  [Schema] SYSNAME NOT NULL,
  [Table] SYSNAME NOT NULL,
  [StartFreeRange] BIGINT NOT NULL,
  [DefaultClaimSize] INT NOT NULL,

  CONSTRAINT [pkIDClaim] PRIMARY KEY NONCLUSTERED ([ID]),
  CONSTRAINT [ucIDClaim] UNIQUE NONCLUSTERED HASH ([Database], [Schema], [Table]) WITH (BUCKET_COUNT = 128)
) WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_AND_DATA);
